spring:
  datasource:
    url: jdbc:oracle:thin:@112.221.156.34:12345:xe
    username: KH01_KHW
    password: KH1234
    driver-class-name: oracle.jdbc.OracleDriver

jwt:
  secret: f7ZdQ5PLwBBkFcDddRvXMbA6vjc45oGQQAF7L7XzR2teltleiweeTrk64agIkP5X2DbzbBETXDBqKxDJpsVOQISLK3P62zEk3FGbiYwG89VZ6LUjJUkxVW9AwpJwAjrD9b0vEYje3B3KeBPu0kZ3CZEeVLRRyO1bdj7BfkhgEaXVvJHDCqgoDlq4qAtfjSkArmYeaqECEEhGXbFvFpcZ8D16WGrsKU3DCYwqFEG2qIcjoXEo5uPtA3MLrbAjoZMG10VcfFxKeVxBYkTYgWvVbWswY9FycLwX2yiMu9K1cyHUKHfysJVXqVsEJuDuEHjIuZ7wGjZ6eAb7uLwQsrYcKUauQxKD7JM1seMrp5fS6IbXsumIEaAyIVtYRYTCS4qXDuMpPuAh4vdT20WS5t3qchvauYMg4F5fcdtcbbhQOIl1Jrud09Ev7w207VeQ1YZASCmgo7eZAsTSIUJouhreDMVSCTdh9TkulgOK6pFzaj9sFb6cWLqEjLJ4qzMDx9ke